
model_params:
  num_resnet_blocks: 16
  num_scales: 3 #L split happens after each scale
  num_step_of_flow: 3 # K each flow step has 6 affine coupling layers
  n_bins:  265

train_params:
  lr: 1.e-3
  batch_size: 128
  epochs: 100
  model_checkpoint_path: "./model_checkpoints"

data_params:
  num_samples: -1
  batch_size: 128
  num_workers: 8
  dataset_name: lsun_bedroom # CelebA or lsun_bedroom

sampling_params:
  num_samples_nrow: 5
  num_samples_ncols: 5
  generate_fixed_images: True
  samples_output_path: ./samples/lsun_bedroom_64*64_3_scales_18_affinelayers_16_resnetblocks